export type LiveSessionStatus = 'scheduled' | 'live' | 'ended' | 'cancelled';
export type LiveSessionType = 'livestream';
export type LiveSessionPrivacy = 'public' | 'private' | 'event_registered_only';
export type RecordingVisibility = 'host_only' | 'registered_members' | 'public_replay';

export type LiveSession = {
  id: string;
  sessionId: string;
  eventId?: string | null;
  eventTitle?: string;
  title: string;
  description?: string | null;
  hostLabel?: string | null;
  startAt?: string | null;
  endAt?: string | null;
  durationMinutes?: number;
  sessionType?: LiveSessionType;
  privacy?: LiveSessionPrivacy;
  status: LiveSessionStatus;
  meetingUrl: string;
  joinLink?: string | null;
  streamUrl?: string | null;
  streamSource?: 'external' | 'built_in';
  recordingUrl?: string | null;
  recordingPath?: string | null;
  recordingExpiresAt?: string | null;
  roomCode?: string | null;
  sessionToken?: string | null;
  viewersCount?: number;
  participantCount?: number;
  activeViewerCount?: number;
  chatEnabled?: boolean;
  allowParticipantMic?: boolean;
  allowParticipantCamera?: boolean;
  allowParticipantScreenshare?: boolean;
  waitingRoomEnabled?: boolean;
  recordingEnabled?: boolean;
  recordingVisibility?: RecordingVisibility;
};

export type LiveSessionFormState = {
  title: string;
  description: string;
  eventId: string;
  hostLabel: string;
  startDate: string;
  startTime: string;
  endDate: string;
  endTime: string;
  status: LiveSessionStatus;
  privacy: LiveSessionPrivacy;
  allowChat: boolean;
  streamSource: 'external' | 'built_in';
  streamUrl: string;
  roomCode: string;
  sessionId: string;
  joinLink: string;
  sessionToken: string;
  recordingEnabled: boolean;
  recordingVisibility: RecordingVisibility;
  saveMode: 'draft' | 'create';
};
